### ISSUE TITLE
gx_get() and gx_put() not working as explained in the tutorial pages

### ISSUE THREAD

**Issue by chufz** [usegalaxy-eu/galaxy#169]
**Describe the bug**
Dear developers, i just tried the studio interactive tool on the galaxy.eu instance. While the opening and the general rstudion session is active,  the access to the galaxy workflow seem not to work at all

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: {"version_major":"23.0","version_minor":"1.dev0"}

**To Reproduce**
1. Run studio
2. Type in command line:

```
data <- read.csv(gx_get(4), sep="\t")
DEBUG:root:Host IP determined to be b'172.17.0.1\n'
DEBUG:root:TestURL url=https://usegalaxy.eu obj=False
/opt/miniconda/lib/python3.9/site-packages/bioblend/galaxy/histories/__init__.py:120: FutureWarning: The history_id parameter is deprecated, use the show_history() method to view details of a history for which you know the ID.
  warnings.warn(
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): usegalaxy.eu:443
DEBUG:urllib3.connectionpool:https://usegalaxy.eu:443 "GET /api/histories HTTP/1.1" 401 61
DEBUG:root:TestURL url=https://usegalaxy.eu state=failure
DEBUG:root:TestURL url=http://b'172.17.0.1':8080 obj=False
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): b'172.17.0.1':8080
DEBUG:root:TestURL url=http://b'172.17.0.1':8080 state=failure
Traceback (most recent call last):
  File "/usr/local/bin/get", line 19, in <module>
    results = get( args.id, args.identifier_type, args.history_id )
  File "/opt/miniconda/lib/python3.9/site-packages/galaxy_ie_helpers/__init__.py", line 167, in get
    gi = get_galaxy_connection(history_id=history_id, obj=False)
  File "/opt/miniconda/lib/python3.9/site-packages/galaxy_ie_helpers/__init__.py", line 100, in get_galaxy_connection
    raise Exception(msg)
Exception: Could not connect to a galaxy instance. Please contact your SysAdmin for help with this error
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file '/import/4': No such file or directory
> put('./my_file.tsv', file_type="tabular")
Error in put("./my_file.tsv", file_type = "tabular") : 
  could not find function "put"
> gx_put('./my_file.tsv', file_type="tabular")
DEBUG:root:Host IP determined to be b'172.17.0.1\n'
DEBUG:root:TestURL url=https://usegalaxy.eu obj=True
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): usegalaxy.eu:443
DEBUG:urllib3.connectionpool:https://usegalaxy.eu:443 "GET /api/histories/cb19bec6de47c5f8 HTTP/1.1" 401 61
DEBUG:root:TestURL url=https://usegalaxy.eu state=failure
DEBUG:root:TestURL url=http://b'172.17.0.1':8080 obj=True
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): b'172.17.0.1':8080
DEBUG:root:TestURL url=http://b'172.17.0.1':8080 state=failure
Traceback (most recent call last):
  File "/usr/local/bin/put", line 17, in <module>
    put( args.filepath, file_type=args.filetype, history_id=args.history_id )
  File "/opt/miniconda/lib/python3.9/site-packages/galaxy_ie_helpers/__init__.py", line 113, in put
    gi = get_galaxy_connection(history_id=history_id)
  File "/opt/miniconda/lib/python3.9/site-packages/galaxy_ie_helpers/__init__.py", line 100, in get_galaxy_connection
    raise Exception(msg)
Exception: Could not connect to a galaxy instance. Please contact your SysAdmin for help with this error```

**Comment by bgruening** [comment]
Hi @chufz,

you are using this tool? https://usegalaxy.eu/root?tool_id=interactive_tool_jupyter_notebook

Please also check that you have an API key set here: https://usegalaxy.eu/user/api_key
I checked it in my account and it seems to work so I assume there is something strange going on with your API key - which is used to communicate between the Juypter Notebook and your Galaxy history.

In general please use: help.galaxyproject.org
This repository is more for the Galaxy framework development.

Thanks for using Galaxy,
Bjoern
